### ISSUE TITLE
re-run should not append additional coffeesalt headers

### ISSUE THREAD

**Issue by d3matt** [trichner/gitc0ffee#2]
Ever run of gitc0ffee adds a new coffeesalt header. There should probably be an option to replace the existing header and to remove the existing header.

**Comment by trichner** [comment]
Yes, indeed. That is correct. That's the shortcut I took ;)

Happy for a PR to fix it!

**Comment by trichner** [comment]
Thanks to @dominick-han to get this done in #3 .
